main: net.conji.thiq.Thiq
name: Thiq
version: 2.0.1
description: NodeJS-like environment for Bukkit/Spigot.
softdepend: [Spout]
commands:
  reloadjs:
    usage: /<command>
    description: Reloads the javascript environment (except persistence. add -p for that)
    permission: thiq.reload