main: net.conji.thiq.Thiq
name: Thiq
version: 3.0.0
description: NodeJS-like environment for Bukkit/Spigot.
commands:
  reloadjs:
    usage: /<command>
    description: Reloads the JavaScript environment.
    permission: thiq.reload